apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: paavan24/mern-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/myLoginDB"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort # Exposes the backend to your laptop
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001 # Access at localhost:30001